version: '3'
services:
    php_shared:
        build:
            context: ./docker
            dockerfile: Dockerfile                 
        container_name: php_shared
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            XDEBUG_MODE: debug,coverage
            XDEBUG_CONFIG: -client_host=host.docker.internal
        volumes:
            - '.:/var/www/html'
        networks:
            - e2ateam        

networks:
    e2ateam:
      driver: bridge
